name: 自动构建
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  build-android:
    if: "github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'release: ')"
    runs-on: ubuntu-latest
    steps:
      - env: 
          REQBODY: ${{github.event.pull_request.body}}
        run: |
          echo "${REQBODY}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Env
        uses: actions/setup-node@v3
        with: 
          node-version: 20
      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # - name: Setup Debug Session
        # uses: csexton/debugger-action@master
      - name: Build
        run: | 
          chmod +x ./gradlew
          ./gradlew assembleRelease
      - name: Generate Changelog
        run: echo github.event_name
  manual: 
    runs-on: ubuntu-latest
    if: "github.event_name == 'workflow_dispatch'"
    steps:
      - env: 
          REQBODY: ${{github.event.pull_request.body}}
        run: |
          echo "${REQBODY}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Env
        uses: actions/setup-node@v3
        with: 
          node-version: 20
      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # - name: Setup Debug Session
        # uses: csexton/debugger-action@master
      - name: Build
        run: | 
          chmod +x ./gradlew
          ./gradlew assembleRelease
      
